env:
  node: true
  es2021: true
  jest/globals: true
extends:
  - "eslint:recommended"
parser: "@typescript-eslint/parser"
plugins:
  - "jest"
  - "@typescript-eslint"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: "./tsconfig.json"
