name: "w3name Action"
author: "Ace Archive"
description: >
  Publish IPNS names with w3name.
inputs:
  private-key:
    description: >
      The base64-encoded private signing key for the IPNS name. This is a
      secret.

      You can create a new private key with the `ipfs key gen` command.
    required: true
  path:
    description: >
      The path the IPNS name should resolve to, like an `/ipfs/xxx` or
      `/ipns/xxx` path.

      If this input is not provided, then the action will attempt to resolve the
      current path associated with the given key and re-publish it.
    required: false
  init:
    description: >
      Create the initial revision of the IPNS name for the given private key.
      You must specify this option if this is the first time this key is being
      used with w3name.

      If you specify this input, then you must also provide a `path`.
    required: false
outputs:
  name:
    description: >
      The published IPNS name.
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: tag
  color: blue
